### ISSUE TITLE
acme packet OS version

### ISSUE THREAD

**Issue by sumagol** [sipcapture/hepfix.js#1]
First Thanks for your great approach!

i'm testing the hepfix.js with 4600 SCZ7.3.0 MR-2 Patch 5.
TCP Handshake works:
```
HEPFIX.js Listening on port 4739 ...
GOT HANDSHAKE ID:  256
REPLYING WITH ID: 257

sbc# show comm-monitor 

16:08:22-127
Client                     State                 Protocol
===========================================================
212.117.192.70:4739        Connected             TCP    
```

but after handshake he sends complete different SetID
```
Cisco NetFlow/IPFIX
    Version: 10
    Length: 20
    Timestamp: Jan  1, 1970 01:00:00.000000000 CET
    FlowSequence: 0
    Observation Domain Id: 0
    Set 1 [id=0] (Data Template):  <--
        FlowSet Id: Data Template (V9) (0)
        FlowSet Length: 4

```

console output of hepfix.js:
```
Invalid/Unsupported Type:  undefined
Invalid/Unsupported Type:  undefined
Invalid/Unsupported Type:  undefined
Invalid/Unsupported Type:  undefined

```
on which ACME OS Version/Platform did you your test?
do you may have a reference for screen ipfix stream?

thanks in advance

**Comment by negbie** [comment]
I am not so deep into this node version but you can try the go version and see if it has this problem too. This is the binary. So just download it here and start it with the proper flags.
https://github.com/negbie/horaclifix/releases/tag/0.80

**Comment by negbie** [comment]
I tested the go version on acme 4250(scz), acme 4500(scz), acme 6300(scz), acme os(ECZ7.3.0 Patch 10)

**Comment by lmangani** [comment]
Highly suggest the GO version from @negbie which probably handles the same packet fine, this JS port is still a work in progress so its going to be useful to know if this is the case to fix it. Thanks!

**Comment by lmangani** [comment]
On the subject....this was by the way the same output scenario which required a reboot of the SD before comm-monitor actually started sending any valid traffic - as @negbie suggested. Could be the case too if it was never used before.

**Comment by sumagol** [comment]
thanks for your fast reply.

> output scenario which required a reboot of the SD before comm-monitor actually started sending any valid traffic

thanks for this great advice, it's for me always the last frustrating thing to do.

i will checkout negbie's horaclifix.

Thanks for your both great work!

**Comment by sumagol** [comment]
> negbie's https://github.com/negbie/horaclifix/releases/tag/0.80

is already running with our AP 4600 SCZ7.3.0 MR-2 Patch 5

Many Thanks!
