### ISSUE TITLE
Question about timestamp delay of 1 minute

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/hepfix.js#3]
Hello,

I do see that packet captured via comm-monitor + hepfix.js, is timestamped 1 minute later than the same packet captured by the other participant.

Do you have any idea it the problem is on the comm-monitor side or in hepfix.js ? 

Regards.

David.

**Comment by lmangani** [comment]
Could you provide an example?

**Comment by dvillaume** [comment]
Hello,

Sorry it was my mistake after checking the false timestamp came from a third source that had bad clock settings and sax this trafic.

Thanks a lot for you availability.
